name: Backend

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Docker build
        uses: docker/build-push-action@v1
        with:
          path: ./backend
          dockerfile: ./backend/server/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: nargonath/do-terraform-nodejs
          tags: latest
